### ISSUE TITLE
RunScript cannot be called with Kodi iOS

### ISSUE THREAD

**Issue by mbologna** [jbinkley60/service.autostop#2]
I am successfully using this plugin with Kodi by adding a `RunScript` into favorites as described [here](https://github.com/jbinkley60/service.autostop/wiki/External-Sleep-Timer-Adjustment).

So far so good, but when I use the remote for Kodi (iOS app) and call the favorite associated to RunScript, I get the error `Cannot do that (type = 'script').`

Is there any workaround?

**Comment by jbinkley60** [comment]
That sounds like a limitation of the Kodi IOS app.  Do you have a link to it where I can take a look at the documentation ?  There may be another way to call the script or you may need to request the Kodi IOS app author extend the functionality to support favorites which have scripts.

**Comment by mbologna** [comment]
> That sounds like a limitation of the Kodi IOS app. Do you have a link to it where I can take a look at the documentation ? There may be another way to call the script or you may need to request the Kodi IOS app author extend the functionality to support favorites which have scripts.

Yes, it might as well be: https://github.com/xbmc/Official-Kodi-Remote-iOS/blob/f432fb19481402da0c060c507a57e3e37b0ba85e/XBMC%20Remote/DetailViewController.m#L1576

**Comment by mbologna** [comment]
Closing the issue here as it is a Kodi iOS limitation.
