### ISSUE TITLE
Feature request: reset sleep timer once it goes off

### ISSUE THREAD

**Issue by mbologna** [jbinkley60/service.autostop#3]
Can it be possible to add an option to have the sleep timer go back to 0 whenever the timer goes off?
Use case: using Autostop as a sleep timer. 
1. The user sets the sleep timer (via the favorite action)
2. User sleeps, Autostop's timer goes off, Kodi stops playing
3. Autostop resets the sleep timer to 0 so next play there is no sleep timer.

**Comment by jbinkley60** [comment]
Yes, that can be added.  How about if I add an addon setting which will enable / disable this feature ?  That way some folks can use it the way it is now and others can set it to reset, like you are asking.

**Comment by mbologna** [comment]
Yes, that would be awesome!

**Comment by jbinkley60** [comment]
Great,  Thanks for the recommendation.  This is a great feature UI never thought of.  I'll post a test version of code tomorrow or Wednesday for you to test before I submit to the Kodi repository.

**Comment by jbinkley60** [comment]
> Yes, that would be awesome!

I have posted a [test release](https://github.com/jbinkley60/service.autostop/tree/1.0.5-Test) with the new feature.  Please test and let me know if it works the way you want.

**Comment by mbologna** [comment]
How can I test it against my Kodi?

**Comment by jbinkley60** [comment]
Sorry I missed your response.  version 1.0.6 of the addon is now in the Kodi repository and you should be able to test it.  You'll see a [new option](https://github.com/jbinkley60/service.autostop/wiki/Autostop-addon-settings) called Sleep Timer reset which does what you requested.

**Comment by mbologna** [comment]
I just tested it and it is working perfectly. Thank you!
