### ISSUE TITLE
Pause Autostop less than 5 Minutes

### ISSUE THREAD

**Issue by pisabird** [jbinkley60/service.autostop#4]
Hi Sir,

Thank you for this great addon. I kindly ask if you could also add the possibility to set seconds, or at least 1 minute?

Best regards,
Rolf

**Comment by jbinkley60** [comment]
You would like the [Pause autostop setting](https://github.com/jbinkley60/service.autostop/wiki/Autostop-addon-settings) to not just be every 5 minutes but also have something like 1 minute ?  Changing over to seconds would be a bit of work but I could add  a 1 minute setting.

**Comment by pisabird** [comment]
One minute would be great 😊 Am 10.08.2024 um 21:03 schrieb jbinkley60 ***@***.***>:﻿
You would like the Pause autostop setting to not just be every 5 minutes but also have something like 1 minute ?  Changing over to seconds would be a bit of work but I could add  a 1 minute setting.

**Comment by jbinkley60** [comment]
I have posted a test [version 1.0.6b here](https://github.com/jbinkley60/service.autostop/tree/1.0.6b-test) which has the 1 minute option.  Please download it and try it and let me know if it works for you.

Jeff

**Comment by pisabird** [comment]
Works fine :)Thank you very much JeffAm 11.08.2024 um 10:51 schrieb jbinkley60 ***@***.***>:﻿
I have posted a test version 1.0.6b here which has the 1 minute option.  Please download it and try it and let me know if it works for you.
Jeff

**Comment by jbinkley60** [comment]
Thanks for confirming.  In the next week or so I'll release this at official version 1.0.7 via the Kodi repository.

Jeff

**Comment by pisabird** [comment]
Good Job 👍 Am 11.08.2024 um 13:14 schrieb jbinkley60 ***@***.***>:﻿
Thanks for confirming.  In the next week or so I'll release this at official version 1.0.7 via the Kodi repository.
Jeff
